//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Code.Game.Scripts.Battle.Items {
    
    
    public sealed class ItemDefType {
        
        public static RG.DefinitionSystem.Core.DefRef<Code.Game.Scripts.Battle.Items.ItemDef> BrokenGlass = "BrokenGlass";
        public static RG.DefinitionSystem.Core.DefRef<Code.Game.Scripts.Battle.Items.ItemDef> Knife = "Knife";
    }
}
