//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Game.UI.Base {
    
    
    public sealed class WidgetPropsType {
        
        public static RG.DefinitionSystem.Core.DefRef<Game.UI.Base.WidgetProps> ItemInfoPanel = "ItemInfoPanel";
    }
}
