//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Code.Game.Scripts.Battle {
    
    
    public sealed class SignDefType {
        
        public static RG.DefinitionSystem.Core.DefRef<Code.Game.Scripts.Battle.SignDef> F = "F";
        
        public static RG.DefinitionSystem.Core.DefRef<Code.Game.Scripts.Battle.SignDef> Goat = "Goat";
        
        public static RG.DefinitionSystem.Core.DefRef<Code.Game.Scripts.Battle.SignDef> Papper = "Papper";
        
        public static RG.DefinitionSystem.Core.DefRef<Code.Game.Scripts.Battle.SignDef> Rock = "Rock";
        
        public static RG.DefinitionSystem.Core.DefRef<Code.Game.Scripts.Battle.SignDef> Scissors = "Scissors";
    }
}
